### ISSUE TITLE
Invite RapidCheck to the challenge

### ISSUE THREAD

**Issue by dubzzz** [jlink/shrinking-challenge#20]
The library [RapidCheck](https://github.com/emil-e/rapidcheck) from @emil-e is the property based testing library I used for a while when doing C++. I believe it could be cool to propose him to join too.

More generally, is it ok if I open issue linking to the challenge on some pbt libs or do you prefer to do it on your side?

**Comment by jlink** [comment]
Go ahead. The more interest the better.

**Comment by dubzzz** [comment]
Thanks, I'll

**Comment by dubzzz** [comment]
Issue opened: https://github.com/emil-e/rapidcheck/issues/270
