### ISSUE TITLE
Submitting a PBT library entry

### ISSUE THREAD

**Issue by flyingmutant** [jlink/shrinking-challenge#21]
I've [implemented](https://github.com/flyingmutant/rapid/blob/master/challenge_external_test.go) most of the challenges (all except the calculator and binary heap) with my Go property-based testing library, [rapid](https://github.com/flyingmutant/rapid). However, I am unsure as to what are the proper steps to generate/submit the reports. Is there any standard tooling available?

**Comment by jlink** [comment]
You can look at the Python tooling, which resides in https://github.com/jlink/shrinking-challenge/tree/main/pbt-libraries/hypothesis/support

For jqwik I generated a report per challenge in a compatible format (see https://github.com/jlink/shrinking-challenge/tree/main/pbt-libraries/jqwik/reports), then used the python script on it and replaced a few strings in the resulting markdown file. This process should be more streamlined but it isn’t until someone finds the time to streamline it.
