### ISSUE TITLE
Would you consider CsCheck?

### ISSUE THREAD

**Issue by AnthonyLloyd** [jlink/shrinking-challenge#22]
It's quite a different approach to most which is having some great benefits in things like concurrency testing.

I could look to add a PR after I've released an upcoming 2.0 version.

https://github.com/AnthonyLloyd/CsCheck

I'm not completely sure of the rules. Is it stats on 100 runs of a test with 100 iterations? CsCheck is slightly different in that if the size isn't small than the failing case it skips the iteration.

**Comment by jlink** [comment]
Sure go ahead with CsCheck. 

It’s a hundred runs with as many tries per run as your framework does by default or by configuration. Eg jqwik does 1000 tries per run unless otherwise configured.
